// ==UserScript==
// @name         Bitbucket UX Improvements
// @namespace    http://tampermonkey.net/
// @version      0.4.0
// @description  Makes some UX improvements to Bitbucket: remove a reviewer by clicking anywhere on their pill, and drop the default reviewers that are irrelevant to the repository
// @author       gthau
// @match        https://bitbucket.org/*
// @icon         https://www.google.com/s2/favicons?sz=64&domain=atlassian.net
// @run-at       document-start
// @updateURL    https://raw.githubusercontent.com/gthau/userscripts/refs/heads/master/src/bitbucket-ux-improvements.user.js
// @downloadURL  https://raw.githubusercontent.com/gthau/userscripts/refs/heads/master/src/bitbucket-ux-improvements.user.js
// @grant        none
// ==/UserScript==

/**
 * Two features on the "create pull request" form:
 *
 * 1. Click anywhere on a reviewer pill to remove that reviewer. The X is a
 *    small target on pills of wildly varying width, so clicking fast down a
 *    list of them is painful. Non-destructive: the worst case is a no-op.
 * 2. On a known repository, remove the default reviewers who are irrelevant to
 *    it. Destructive -- it edits a real PR -- so it is held to a higher bar:
 *    every removal is verified, it refuses to act when the DOM does not look
 *    the way it expects, and it stops as soon as the user touches the field.
 *
 * The page is a React app that remounts freely, and removing a reviewer often
 * replaces the whole picker. So the rule throughout is: hold no node reference
 * across an await, and assume no action took until the DOM says it did. State
 * an intended end state, then re-read until it holds.
 *
 * Bitbucket is also a single-page app, which is why `@match` covers the whole
 * site rather than the form. `@match` only governs injection, and Tampermonkey
 * evaluates it when the document loads, never again on a history rewrite:
 * opening the form from the branch list or the pull request list would
 * otherwise never inject the script at all, and no code in the page can correct
 * that afterwards. `onCreatePullRequestForm` is the gate instead. It is read at
 * the moment of acting rather than once at startup, because the route can
 * change under a script that is already running -- including mid-prune.
 */
(function () {
  "use strict";

  // --------------------------------------------------------------- reviewers

  const REPOS = {
    rundownLib: "rundown-lib",
    rundownApi: "rundown-api",
    scriptEditor: "script-editor-app",
  };

  const RUNDOWN_DEFAULT_REVIEWERS = [
    "ghislain thau",
    "shahar dadon",
    "nufar michurin",
    "revital kimhi",
  ];

  const SCRIPT_EDITOR_DEFAULT_REVIEWERS = [
    "eugene krasner",
    "aviad belulu",
    "amir israel cohen",
    "avivit eitan",
    "stanislav karavaev",
    "cohavit taboch",
    ...RUNDOWN_DEFAULT_REVIEWERS,
  ];

  // Single source of truth for "known repository": a repository is known iff we
  // know who its reviewers are. Deriving the check from this table means adding
  // a repository to `REPOS` alone can no longer produce a lookup on undefined.
  const DEFAULT_REVIEWERS = {
    [REPOS.rundownLib]: RUNDOWN_DEFAULT_REVIEWERS,
    [REPOS.rundownApi]: RUNDOWN_DEFAULT_REVIEWERS,
    [REPOS.scriptEditor]: SCRIPT_EDITOR_DEFAULT_REVIEWERS,
  };

  // ------------------------------------------------------------- DOM contract

  /**
   * Everything this script needs from Bitbucket's DOM, in one place, because
   * this is what breaks when Atlassian ships a redesign.
   *
   * The reviewer field is a react-select with a fixed `classNamePrefix`, so
   * these names are chosen by Atlassian rather than generated by CSS-in-JS,
   * which is why they are usable at all. They are still internal: `probeMount`
   * checks them on every mount and says so on the page when one rots.
   *
   * Assumes the reviewers picker is the only user picker on the form. `@match`
   * no longer says so -- it covers the site, see the note at the top -- so the
   * route gate on the queries below is what keeps this true.
   */
  const CLS = {
    control: "fabric-user-picker__control",
    input: "fabric-user-picker__input",
    inputContainer: "fabric-user-picker__input-container",
    pill: "fabric-user-picker__multi-value",
    pillLabel: "fabric-user-picker__multi-value__label",
    removeBtn: "fabric-user-picker__multi-value__remove",
  };
  const REVIEWERS_LABEL_ID = "reviewer-field-label";

  const MOUNT_ANIMATION = "gt-bb-picker-mounted";
  const STYLE_ID = "gt-bb-ux-style";
  const BADGE_ID = "gt-bb-ux-badge";
  const DRY_RUN_KEY = "gt-bb-dryrun";

  // A removal is a local React state update, so it lands within a frame or two;
  // the budget only has to absorb a few retries, not a slow network.
  const MAX_PRUNE_PASSES = 12;
  const REMOVAL_TIMEOUT_MS = 1_000;
  // Bitbucket fetches the default reviewers after rendering the empty control.
  const FIRST_PILL_TIMEOUT_MS = 15_000;
  const MOUNT_BACKSTOP_MS = 3_000;

  const LOGGER_PREFIX = "[Bitbucket UX improvements] ";
  const logger = {
    log: (message, ...objects) =>
      console.log(LOGGER_PREFIX + message, ...objects),
    debug: (message, ...objects) =>
      console.debug(LOGGER_PREFIX + message, ...objects),
    warn: (message, ...objects) =>
      console.warn(LOGGER_PREFIX + message, ...objects),
    error: (message, ...objects) =>
      console.error(LOGGER_PREFIX + message, ...objects),
  };

  /**
   * `localStorage.setItem("gt-bb-dryrun", "1")` logs what the prune would remove
   * without touching the form. This is how to re-validate the selectors on a
   * live PR after Bitbucket moves something, instead of risking a real reviewer
   * list to find out.
   */
  function isDryRun() {
    try {
      return localStorage.getItem(DRY_RUN_KEY) === "1";
    } catch {
      return false; // partitioned or blocked storage
    }
  }

  // ------------------------------------------------------------------ queries

  /**
   * Are we on the "create pull request" form? Everything this script touches is
   * on that form, and the two queries below answer `null` anywhere else, so the
   * gate does not have to be repeated at each of their call sites. Gating the
   * queries rather than the entry points also covers the awkward case: a
   * navigation away part-way through a prune empties the pill list, which stops
   * the loop the same way an empty form does, instead of letting it carry on
   * against the reviewers field of whatever page we landed on.
   *
   * The workspace is named here because `@match` used to name it and no longer
   * can. It keeps the reach exactly what it was: `REPOS` holds bare repository
   * names, so without it a repository called `rundown-lib` in a stranger's
   * workspace would be pruned against our reviewer list.
   */
  const CREATE_PR_PATH_RE = /^\/ooyalaflex\/[^/]+\/pull-requests\/new(?:\/|$)/;

  const onCreatePullRequestForm = () =>
    CREATE_PR_PATH_RE.test(location.pathname);

  const getControlElt = () =>
    onCreatePullRequestForm()
      ? document.querySelector("." + CLS.control)
      : null;

  const getReviewersLabelElt = () =>
    onCreatePullRequestForm()
      ? document.getElementById(REVIEWERS_LABEL_ID)
      : null;

  const getRepository = () => document.location.pathname.split("/")[2] ?? "";

  /**
   * Always queried from the document, never from a control captured earlier: a
   * removal frequently replaces the picker, and a node React has thrown away
   * keeps answering with the pills it had at the time.
   */
  function getPillElts() {
    const controlElt = getControlElt();
    return controlElt
      ? Array.from(controlElt.querySelectorAll("." + CLS.pill))
      : [];
  }

  /**
   * Read a pill's reviewer name, or `null` when the DOM does not look the way
   * we expect. Scoped to the label element rather than the pill's whole
   * `textContent`, which also covers the remove button's subtree and would
   * start returning junk the day Atlassian puts a tooltip in there.
   */
  function readReviewerName(pillElt) {
    const label = pillElt.querySelector("." + CLS.pillLabel);
    const name = (label?.textContent ?? "").trim();
    return name || null;
  }

  const normalize = (name) =>
    name
      .normalize("NFKD")
      .replace(/\p{Diacritic}/gu, "")
      .replace(/\s+/g, " ")
      .trim()
      .toLowerCase(); // not toLocaleLowerCase: compared against ASCII literals

  /**
   * "Cannot tell" counts as relevant, i.e. keep the reviewer. A false keep
   * costs one manual click; a false remove silently drops someone from the PR
   * and nobody notices until the review stalls.
   */
  function isRelevantDefaultReviewer(pillElt, relevantNames) {
    const name = readReviewerName(pillElt);
    if (!name) {
      logger.warn("could not read a reviewer's name, keeping them", pillElt);
      return true;
    }
    return relevantNames.includes(normalize(name));
  }

  // ------------------------------------------------------------------ waiting

  /**
   * Resolve with the predicate's first truthy value, or `null` on timeout or
   * abort. Waiting on mutations instead of a fixed delay is faster on a warm
   * page and still correct on a cold one.
   *
   * The root defaults to the document element on purpose. Observing the picker
   * would be narrower, but the picker is exactly what a removal replaces, and
   * an observer bound to a discarded node never fires again -- which turns
   * every verification into a timeout. `childList` alone is enough to notice a
   * pill appearing or disappearing, and keeps the callback rate down on what is
   * a busy React page.
   */
  function waitFor(predicate, { root, timeoutMs, signal } = {}) {
    return new Promise((resolve) => {
      const found = predicate();
      if (found) return resolve(found);
      if (signal?.aborted) return resolve(null);

      let observer;
      let timer;
      const finish = (value) => {
        observer.disconnect();
        clearTimeout(timer);
        signal?.removeEventListener("abort", onAbort);
        resolve(value);
      };
      const onAbort = () => finish(null);

      observer = new MutationObserver(() => {
        const value = predicate();
        if (value) finish(value);
      });
      timer = setTimeout(() => finish(null), timeoutMs);
      signal?.addEventListener("abort", onAbort, { once: true });
      observer.observe(root ?? document.documentElement ?? document, {
        childList: true,
        subtree: true,
      });
    });
  }

  /**
   * Drive the DOM towards an end state instead of firing a batch of clicks at
   * it: one action per pass, each one verified, re-reading in between. A
   * dropped click, a re-render mid-flight or a slow server costs another pass
   * rather than corrupting the result, the whole thing is safe to run twice,
   * and running out of budget is loud instead of silent.
   *
   * `actOnce` returns false to stop, and logs why it stopped.
   */
  async function converge({ name, isGoalReached, actOnce, budget, signal }) {
    for (let pass = 0; pass <= budget; pass++) {
      if (signal.aborted) {
        logger.debug(`${name}: aborted after ${pass} pass(es)`);
        return;
      }
      if (isGoalReached()) {
        logger.debug(`${name}: reached after ${pass} pass(es)`);
        return;
      }
      if (!(await actOnce())) {
        logger.debug(`${name}: stopped after ${pass} pass(es)`);
        return;
      }
    }
    logger.warn(
      `${name}: still not reached after ${budget} passes, leaving the DOM as-is`
    );
  }

  // ------------------------------------------------------ remove by one click

  /**
   * Delegated to `document` and registered once. Click events bubble, so this
   * cannot go stale: React is free to remount the picker as often as it likes
   * without leaving us bound to a node nobody can see any more.
   */
  function removeReviewerBySimpleClick(event) {
    // This one reaches the pill through the event rather than through the
    // gated queries, and it is bound for the life of the tab. Without the
    // route check, a click on a reviewer pill anywhere on Bitbucket -- an open
    // pull request's reviewers field, say -- would remove that reviewer.
    if (!onCreatePullRequestForm()) return;

    const target = event.target;
    if (!(target instanceof Element)) return;

    // The X already does the right thing; re-dispatching on it would hand React
    // the same removal twice.
    if (target.closest("." + CLS.removeBtn)) return;
    if (target.closest(`.${CLS.input}, .${CLS.inputContainer}`)) return;

    const pillElt = target.closest("." + CLS.pill);
    if (!pillElt?.closest("." + CLS.control)) return;

    const removeBtn = pillElt.querySelector("." + CLS.removeBtn);
    if (!removeBtn) {
      logger.warn("no remove button inside the clicked reviewer pill", pillElt);
      return;
    }
    removeBtn.click();
  }

  // ----------------------------------------------------------- prune on mount

  /**
   * Remove one pill and wait until a reviewer has really gone. Progress is
   * measured by re-counting through `countIrrelevant`, so it stays true whether
   * React updated the picker in place or replaced it wholesale.
   *
   * Returns false only when there is structurally nothing left to try, so a
   * click that failed to land is retried rather than treated as final.
   */
  async function removeOnePill({ pillElt, countIrrelevant, signal }) {
    if (!pillElt) {
      logger.debug(
        getControlElt()
          ? "no reviewer left to remove"
          : "the reviewers field is gone"
      );
      return false;
    }
    // Re-rendered between the query and now: just take another pass.
    if (!pillElt.isConnected) return true;

    const removeBtn = pillElt.querySelector("." + CLS.removeBtn);
    if (!removeBtn) {
      logger.warn("no remove button inside a reviewer pill", pillElt);
      return false;
    }

    const name = readReviewerName(pillElt) ?? "an unnamed reviewer";
    const before = countIrrelevant();
    removeBtn.click();

    const removed = await waitFor(() => countIrrelevant() < before, {
      timeoutMs: REMOVAL_TIMEOUT_MS,
      signal,
    });
    if (removed) {
      logger.debug(`removed ${name}`);
    } else if (!signal.aborted) {
      logger.debug(`the click on ${name} did not take, retrying`);
    }
    return true;
  }

  async function pruneIrrelevantDefaultReviewers(repository, signal) {
    const relevantNames = DEFAULT_REVIEWERS[repository].map(normalize);
    const irrelevantPills = () =>
      getPillElts().filter(
        (pillElt) => !isRelevantDefaultReviewer(pillElt, relevantNames)
      );
    const countIrrelevant = () => irrelevantPills().length;

    const pillCount = getPillElts().length;
    const names = irrelevantPills().map((pillElt) => readReviewerName(pillElt));

    if (names.length === 0) {
      logger.debug(`every default reviewer belongs on a ${repository} PR`);
      return;
    }

    // If every reviewer looks irrelevant then the table above is stale, not the
    // page. Refuse: emptying the field is the failure that actually costs
    // review time, and it looks exactly like the script working correctly.
    if (names.length === pillCount) {
      reportBrokenContract(
        `none of the ${pillCount} default reviewers is known for ${repository}`
      );
      logger.warn("refusing to clear the reviewer field", names);
      return;
    }

    logger.debug(
      `removing ${names.length} of ${pillCount} default reviewer(s) as irrelevant to ${repository}`,
      names
    );
    if (isDryRun()) {
      logger.log("dry run: leaving the reviewer field untouched");
      return;
    }

    await converge({
      name: "prune default reviewers",
      isGoalReached: () => !!getControlElt() && countIrrelevant() === 0,
      actOnce: () => {
        // The route gate on the queries stops a prune that outlives the form.
        // This stops the narrower case it cannot see: the form for a different
        // repository, whose reviewers answer to a different list from the one
        // these pills are being judged against.
        if (getRepository() !== repository) {
          logger.debug(`no longer on a ${repository} pull request`);
          return false;
        }
        return removeOnePill({
          pillElt: irrelevantPills()[0],
          countIrrelevant,
          signal,
        });
      },
      budget: MAX_PRUNE_PASSES,
      signal,
    });

    // Close the picker the user never asked to open.
    if (!signal.aborted) getReviewersLabelElt()?.click();
  }

  /**
   * The user's intent outranks ours the moment they touch the field, including
   * mid-prune. Delegated to `document` because the picker we would otherwise
   * bind to gets replaced on every removal, taking its listeners with it.
   *
   * `isTrusted` is the one place where telling synthetic events from real ones
   * works in our favour: without it our own removal clicks would abort us.
   */
  function abortOnUserInteraction() {
    const controller = new AbortController();
    const abort = (event) => {
      if (!event.isTrusted) return;
      if (!(event.target instanceof Element)) return;
      if (!event.target.closest("." + CLS.control)) return;
      logger.debug(`the user interacted (${event.type}), stopping the prune`);
      controller.abort();
    };
    for (const type of ["pointerdown", "mousedown", "keydown"]) {
      document.addEventListener(type, abort, {
        capture: true,
        signal: controller.signal,
      });
    }
    return controller;
  }

  // A prune replaces the picker on every removal, so it sees a stream of fresh
  // mounts of its own making. One at a time; a second is a cheap no-op once the
  // first has converged.
  let prunePromise = null;

  function prunePickerOnce(repository) {
    if (prunePromise) return prunePromise;

    const controller = abortOnUserInteraction();
    prunePromise = pruneIrrelevantDefaultReviewers(
      repository,
      controller.signal
    ).finally(() => {
      controller.abort(); // also unbinds the listeners above
      prunePromise = null;
    });
    return prunePromise;
  }

  /**
   * Check the DOM contract once per mount, and let the two features fail
   * independently: clicking a pill to remove it only needs the pill and its X,
   * while the prune also has to read names correctly, and a misread name means
   * dropping the wrong person from a PR.
   */
  function probeMount(pillElt) {
    if (!pillElt.querySelector("." + CLS.removeBtn)) {
      return { canPrune: false, reason: `no .${CLS.removeBtn} inside a pill` };
    }
    if (!pillElt.querySelector("." + CLS.pillLabel)) {
      return { canPrune: false, reason: `no .${CLS.pillLabel} inside a pill` };
    }
    return { canPrune: true };
  }

  // A WeakSet keyed on the control node replaces a `firstTime` flag: a remount
  // hands us a new node, so we look again; the mount backstop hands us the same
  // node, so we skip. Nothing to keep in sync and nothing to leak.
  const handledControls = new WeakSet();

  async function onPickerMounted(controlElt) {
    // The node arrives from the mount event, not from `getControlElt`, so the
    // gate is repeated here. Before the WeakSet rather than after: a picker
    // seen elsewhere on Bitbucket must not be recorded as one we have dealt
    // with. A prune is the destructive feature, and off this form the field it
    // would edit belongs to a pull request that already exists.
    if (!onCreatePullRequestForm()) return;

    if (handledControls.has(controlElt)) return;
    handledControls.add(controlElt);

    const repository = getRepository();
    if (!(repository in DEFAULT_REVIEWERS)) {
      logger.debug(`no reviewer list for ${repository}, nothing to prune`);
      return;
    }
    logger.debug(`reviewers control mounted on ${repository}`);

    const firstPill = await waitFor(() => getPillElts()[0], {
      timeoutMs: FIRST_PILL_TIMEOUT_MS,
    });
    if (!firstPill) {
      logger.debug("no default reviewer appeared, nothing to prune");
      return;
    }

    const { canPrune, reason } = probeMount(firstPill);
    if (!canPrune) {
      // Click-to-remove is delegated and unconditional, so it keeps working.
      reportBrokenContract(reason);
      return;
    }

    await prunePickerOnce(repository);
  }

  // ------------------------------------------------------------- diagnostics

  /**
   * A `console.warn` nobody reads is not a report: the devtools are closed
   * while you are actually filing a PR, and a script whose selectors have
   * rotted looks exactly like a script with nothing to do. Say it on the page.
   */
  function reportBrokenContract(reason) {
    logger.warn(`DOM contract broken: ${reason}`);
    if (document.getElementById(BADGE_ID)) return;

    const badge = document.createElement("div");
    badge.id = BADGE_ID;
    badge.textContent = `⚠️ Bitbucket UX script: ${reason}`;
    badge.title =
      "This userscript's selectors need updating. Click to dismiss.";
    badge.addEventListener("click", () => badge.remove());
    (document.body ?? document.documentElement).append(badge);
  }

  /** One uncaught throw must not take out the listener that would recover. */
  function guard(fn) {
    try {
      Promise.resolve(fn()).catch((e) => logger.error("failed", e));
    } catch (e) {
      logger.error("failed", e);
    }
  }

  function injectStyle(id, css) {
    const style =
      document.getElementById(id) ?? document.createElement("style");
    style.id = id;
    style.textContent = css;
    // At document-start there may be no <head> yet, and a <style> applies from
    // anywhere in the document.
    (document.head ?? document.documentElement).append(style);
  }

  // ------------------------------------------------------------------ startup

  // The browser knows the instant the control renders and will say so through
  // `animationstart`. That beats polling on three counts: no dead time before a
  // first tick, no permanent subtree observer over a heavy React page, and it
  // fires again on every remount -- so reaching the form by a soft navigation
  // is the same event as reaching it by a page load, and the rule has to be in
  // the document from the start for a form that arrives later to be caught.
  // Same lever as the Jira fixVersion script's ::after rules: let CSS reach the
  // nodes React has not created yet, here for detection rather than decoration.
  // `outline-color` is animated because it changes nothing visible.
  injectStyle(
    STYLE_ID,
    `@keyframes ${MOUNT_ANIMATION} {
  from { outline-color: currentColor; }
  to { outline-color: currentColor; }
}
.${CLS.control} { animation: ${MOUNT_ANIMATION} 1ms linear; }
#${BADGE_ID} {
  position: fixed;
  inset-block-end: 1rem;
  inset-inline-end: 1rem;
  z-index: 2147483647;
  max-width: 24rem;
  padding: 0.5rem 0.75rem;
  border-radius: 4px;
  background: #fff4e5;
  color: #442c00;
  border: 1px solid #f5cd90;
  font: 0.8rem/1.4 sans-serif;
  cursor: pointer;
}`
  );

  document.addEventListener(
    "animationstart",
    (event) => {
      if (event.animationName !== MOUNT_ANIMATION) return;
      guard(() => onPickerMounted(event.target));
    },
    true
  );

  document.addEventListener("click", removeReviewerBySimpleClick);

  // Backstop for the one thing the animation trick cannot survive: page CSS
  // winning over `animation` on the control. Idempotent thanks to the WeakSet,
  // so on the form it costs one querySelector, and everywhere else on
  // Bitbucket -- which `@match` no longer excludes -- one regular expression.
  setInterval(() => {
    const controlElt = getControlElt();
    if (controlElt) guard(() => onPickerMounted(controlElt));
  }, MOUNT_BACKSTOP_MS);
})();
